name: CD
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy production
    runs-on: ubuntu-latest
    environment: 'production'
    steps:
      - name: Hacer checkout
        uses: actions/checkout@v4

      - name: make build
        run: |
          npm ci --legacy-peer-deps
          npm run build
          npm prune --omit=dev

      - name: Deploy Mensaje
        run: |
          echo "Deploy Hola Mundo!"
